// 500+ unique user names for payout display across 20+ countries

export interface NameEntry {
    name: string;
    country: string;
    flag: string;
}

export const ALL_NAMES: NameEntry[] = [
    // ── INDIA (130 names) ──────────────────────────────────────────────────
    { name: "Raj Kapoor", country: "India", flag: "🇮🇳" },
    { name: "Priya Sharma", country: "India", flag: "🇮🇳" },
    { name: "Arjun Mehta", country: "India", flag: "🇮🇳" },
    { name: "Ananya Patel", country: "India", flag: "🇮🇳" },
    { name: "Vikram Rao", country: "India", flag: "🇮🇳" },
    { name: "Ishaan Tiwari", country: "India", flag: "🇮🇳" },
    { name: "Diya Nair", country: "India", flag: "🇮🇳" },
    { name: "Rohan Singh", country: "India", flag: "🇮🇳" },
    { name: "Aditya Kumar", country: "India", flag: "🇮🇳" },
    { name: "Kavya Bose", country: "India", flag: "🇮🇳" },
    { name: "Sanjay Dubey", country: "India", flag: "🇮🇳" },
    { name: "Neha Verma", country: "India", flag: "🇮🇳" },
    { name: "Karan Gupta", country: "India", flag: "🇮🇳" },
    { name: "Sneha Lal", country: "India", flag: "🇮🇳" },
    { name: "Aarav Walia", country: "India", flag: "🇮🇳" },
    { name: "Riya Chaudhary", country: "India", flag: "🇮🇳" },
    { name: "Amit Joshi", country: "India", flag: "🇮🇳" },
    { name: "Pooja Hegde", country: "India", flag: "🇮🇳" },
    { name: "Deepak Malhotra", country: "India", flag: "🇮🇳" },
    { name: "Shreya Agarwal", country: "India", flag: "🇮🇳" },
    { name: "Nikhil Pandey", country: "India", flag: "🇮🇳" },
    { name: "Anjali Reddy", country: "India", flag: "🇮🇳" },
    { name: "Rahul Das", country: "India", flag: "🇮🇳" },
    { name: "Meera Krishnan", country: "India", flag: "🇮🇳" },
    { name: "Siddharth Banerjee", country: "India", flag: "🇮🇳" },
    { name: "Nisha Ghosh", country: "India", flag: "🇮🇳" },
    { name: "Varun Sen", country: "India", flag: "🇮🇳" },
    { name: "Akshara Menon", country: "India", flag: "🇮🇳" },
    { name: "Harsh Vardhan", country: "India", flag: "🇮🇳" },
    { name: "Tanya Luthra", country: "India", flag: "🇮🇳" },
    { name: "Yash Trivedi", country: "India", flag: "🇮🇳" },
    { name: "Isha Nawaz", country: "India", flag: "🇮🇳" },
    { name: "Kunal Wankhede", country: "India", flag: "🇮🇳" },
    { name: "Divya Chatterjee", country: "India", flag: "🇮🇳" },
    { name: "Manish Handa", country: "India", flag: "🇮🇳" },
    { name: "Simran Juneja", country: "India", flag: "🇮🇳" },
    { name: "Abhishek Rana", country: "India", flag: "🇮🇳" },
    { name: "Sapna Roy", country: "India", flag: "🇮🇳" },
    { name: "Vishal Khanna", country: "India", flag: "🇮🇳" },
    { name: "Tanvi Bhatia", country: "India", flag: "🇮🇳" },
    { name: "Tarun Saxena", country: "India", flag: "🇮🇳" },
    { name: "Ritika Mishra", country: "India", flag: "🇮🇳" },
    { name: "Shubham Dhawan", country: "India", flag: "🇮🇳" },
    { name: "Kriti Pillai", country: "India", flag: "🇮🇳" },
    { name: "Gaurav Lamba", country: "India", flag: "🇮🇳" },
    { name: "Megha Vyas", country: "India", flag: "🇮🇳" },
    { name: "Mohit Anand", country: "India", flag: "🇮🇳" },
    { name: "Swati Garg", country: "India", flag: "🇮🇳" },
    { name: "Pankaj Rastogi", country: "India", flag: "🇮🇳" },
    { name: "Nidhi Thakur", country: "India", flag: "🇮🇳" },
    { name: "Samir Naik", country: "India", flag: "🇮🇳" },
    { name: "Pallavi Kulkarni", country: "India", flag: "🇮🇳" },
    { name: "Rajesh Mistry", country: "India", flag: "🇮🇳" },
    { name: "Lata Shah", country: "India", flag: "🇮🇳" },
    { name: "Suresh Babu", country: "India", flag: "🇮🇳" },
    { name: "Seema Deshpande", country: "India", flag: "🇮🇳" },
    { name: "Naveen Hoogar", country: "India", flag: "🇮🇳" },
    { name: "Preeti Warrier", country: "India", flag: "🇮🇳" },
    { name: "Ramesh Chand", country: "India", flag: "🇮🇳" },
    { name: "Sunita Jayaram", country: "India", flag: "🇮🇳" },
    { name: "Ravi Prakash", country: "India", flag: "🇮🇳" },
    { name: "Swapna Iyer", country: "India", flag: "🇮🇳" },
    { name: "Dinesh Pawar", country: "India", flag: "🇮🇳" },
    { name: "Geeta Bhatt", country: "India", flag: "🇮🇳" },
    { name: "Pavan Kumar", country: "India", flag: "🇮🇳" },
    { name: "Rekha Dev", country: "India", flag: "🇮🇳" },
    { name: "Vijay Raghavan", country: "India", flag: "🇮🇳" },
    { name: "Sheetal Mohan", country: "India", flag: "🇮🇳" },
    { name: "Ajay Hiremath", country: "India", flag: "🇮🇳" },
    { name: "Meenakshi Rao", country: "India", flag: "🇮🇳" },
    { name: "Santosh Naidu", country: "India", flag: "🇮🇳" },
    { name: "Anita Srivastava", country: "India", flag: "🇮🇳" },
    { name: "Karthik Pillai", country: "India", flag: "🇮🇳" },
    { name: "Padma Subramaniam", country: "India", flag: "🇮🇳" },
    { name: "Sunil Dixit", country: "India", flag: "🇮🇳" },
    { name: "Lalita Goswami", country: "India", flag: "🇮🇳" },
    { name: "Arun Khosla", country: "India", flag: "🇮🇳" },
    { name: "Veda Krishnaswamy", country: "India", flag: "🇮🇳" },
    { name: "Girish Nambiar", country: "India", flag: "🇮🇳" },
    { name: "Archana Pillai", country: "India", flag: "🇮🇳" },
    { name: "Chirag Bhansali", country: "India", flag: "🇮🇳" },
    { name: "Anuradha Murthy", country: "India", flag: "🇮🇳" },
    { name: "Dhruv Khare", country: "India", flag: "🇮🇳" },
    { name: "Harshita Bendre", country: "India", flag: "🇮🇳" },
    { name: "Pranav Jain", country: "India", flag: "🇮🇳" },
    { name: "Rutuja Patil", country: "India", flag: "🇮🇳" },
    { name: "Sahil Oberoi", country: "India", flag: "🇮🇳" },
    { name: "Vidya Sathe", country: "India", flag: "🇮🇳" },
    { name: "Ujjwal Sinha", country: "India", flag: "🇮🇳" },
    { name: "Kavita Kamat", country: "India", flag: "🇮🇳" },
    { name: "Nitin Deore", country: "India", flag: "🇮🇳" },
    { name: "Shweta Ingale", country: "India", flag: "🇮🇳" },
    { name: "Devendra Fulari", country: "India", flag: "🇮🇳" },
    { name: "Namrata Desai", country: "India", flag: "🇮🇳" },
    { name: "Kaushik Mondal", country: "India", flag: "🇮🇳" },
    { name: "Bhavna Raval", country: "India", flag: "🇮🇳" },
    { name: "Tejas Wagh", country: "India", flag: "🇮🇳" },
    { name: "Amruta Shinde", country: "India", flag: "🇮🇳" },
    { name: "Prasad Kulkarni", country: "India", flag: "🇮🇳" },
    { name: "Alka Nikam", country: "India", flag: "🇮🇳" },
    { name: "Niraj Bhide", country: "India", flag: "🇮🇳" },
    { name: "Varsha Gaikwad", country: "India", flag: "🇮🇳" },
    { name: "Omkar Mane", country: "India", flag: "🇮🇳" },
    { name: "Harsha Jadhav", country: "India", flag: "🇮🇳" },
    { name: "Aadit Thakker", country: "India", flag: "🇮🇳" },
    { name: "Ketki Deshpande", country: "India", flag: "🇮🇳" },
    { name: "Saurabh Bhave", country: "India", flag: "🇮🇳" },
    { name: "Rujuta Paranjpe", country: "India", flag: "🇮🇳" },
    { name: "Siddhesh Khedekar", country: "India", flag: "🇮🇳" },
    { name: "Smita Damle", country: "India", flag: "🇮🇳" },
    { name: "Mihir Gokhale", country: "India", flag: "🇮🇳" },
    { name: "Leena Jog", country: "India", flag: "🇮🇳" },
    { name: "Rohit Dravid", country: "India", flag: "🇮🇳" },
    { name: "Madhuri Karandikar", country: "India", flag: "🇮🇳" },
    { name: "Sumit Karnik", country: "India", flag: "🇮🇳" },
    { name: "Pallabi Bose", country: "India", flag: "🇮🇳" },
    { name: "Indranil Dutta", country: "India", flag: "🇮🇳" },
    { name: "Mousumi Ghosh", country: "India", flag: "🇮🇳" },
    { name: "Subhajit Das", country: "India", flag: "🇮🇳" },
    { name: "Trisha Mukherjee", country: "India", flag: "🇮🇳" },
    { name: "Arnab Chatterjee", country: "India", flag: "🇮🇳" },
    { name: "Suchandra Roy", country: "India", flag: "🇮🇳" },
    { name: "Soumyajit Banerjee", country: "India", flag: "🇮🇳" },
    { name: "Rituparna Sen", country: "India", flag: "🇮🇳" },

    // ── UNITED STATES (60 names) ───────────────────────────────────────────
    { name: "Michael Reynolds", country: "United States", flag: "🇺🇸" },
    { name: "Jessica Thompson", country: "United States", flag: "🇺🇸" },
    { name: "David Lawson", country: "United States", flag: "🇺🇸" },
    { name: "Sarah Mitchell", country: "United States", flag: "🇺🇸" },
    { name: "James Wilson", country: "United States", flag: "🇺🇸" },
    { name: "Emily Davis", country: "United States", flag: "🇺🇸" },
    { name: "Robert King", country: "United States", flag: "🇺🇸" },
    { name: "Jennifer Brown", country: "United States", flag: "🇺🇸" },
    { name: "Christopher Hall", country: "United States", flag: "🇺🇸" },
    { name: "Amanda Scott", country: "United States", flag: "🇺🇸" },
    { name: "Matthew Peterson", country: "United States", flag: "🇺🇸" },
    { name: "Ashley Nelson", country: "United States", flag: "🇺🇸" },
    { name: "Daniel Foster", country: "United States", flag: "🇺🇸" },
    { name: "Lauren Green", country: "United States", flag: "🇺🇸" },
    { name: "Andrew Vincent", country: "United States", flag: "🇺🇸" },
    { name: "Megan Carter", country: "United States", flag: "🇺🇸" },
    { name: "Joshua Rivera", country: "United States", flag: "🇺🇸" },
    { name: "Rachel Adams", country: "United States", flag: "🇺🇸" },
    { name: "Brandon Lewis", country: "United States", flag: "🇺🇸" },
    { name: "Stephanie Knight", country: "United States", flag: "🇺🇸" },
    { name: "Tyler Morgan", country: "United States", flag: "🇺🇸" },
    { name: "Nicole Evans", country: "United States", flag: "🇺🇸" },
    { name: "Justin Bailey", country: "United States", flag: "🇺🇸" },
    { name: "Brittany Warren", country: "United States", flag: "🇺🇸" },
    { name: "Kevin Dixon", country: "United States", flag: "🇺🇸" },
    { name: "Samantha Jenkins", country: "United States", flag: "🇺🇸" },
    { name: "Ryan Howard", country: "United States", flag: "🇺🇸" },
    { name: "Taylor Sullivan", country: "United States", flag: "🇺🇸" },
    { name: "Nathan Parker", country: "United States", flag: "🇺🇸" },
    { name: "Kayla Torres", country: "United States", flag: "🇺🇸" },
    { name: "Aaron Griffin", country: "United States", flag: "🇺🇸" },
    { name: "Heather Coleman", country: "United States", flag: "🇺🇸" },
    { name: "Patrick Reed", country: "United States", flag: "🇺🇸" },
    { name: "Amber Brooks", country: "United States", flag: "🇺🇸" },
    { name: "Ethan Richardson", country: "United States", flag: "🇺🇸" },
    { name: "Allison Edwards", country: "United States", flag: "🇺🇸" },
    { name: "Scott Murphy", country: "United States", flag: "🇺🇸" },
    { name: "Melissa Cook", country: "United States", flag: "🇺🇸" },
    { name: "Gregory Price", country: "United States", flag: "🇺🇸" },
    { name: "Crystal Ward", country: "United States", flag: "🇺🇸" },
    { name: "Sean Simmons", country: "United States", flag: "🇺🇸" },
    { name: "Vanessa Russell", country: "United States", flag: "🇺🇸" },
    { name: "Keith Alexander", country: "United States", flag: "🇺🇸" },
    { name: "Monica Patterson", country: "United States", flag: "🇺🇸" },
    { name: "Jeremy Stone", country: "United States", flag: "🇺🇸" },
    { name: "Danielle Hunt", country: "United States", flag: "🇺🇸" },
    { name: "Bryan Kennedy", country: "United States", flag: "🇺🇸" },
    { name: "Renee Olson", country: "United States", flag: "🇺🇸" },
    { name: "Dennis Bishop", country: "United States", flag: "🇺🇸" },
    { name: "Candace Arnold", country: "United States", flag: "🇺🇸" },
    { name: "Shawn Harrison", country: "United States", flag: "🇺🇸" },
    { name: "Tiffany Rogers", country: "United States", flag: "🇺🇸" },
    { name: "Cody Crawford", country: "United States", flag: "🇺🇸" },
    { name: "Lindsey Cunningham", country: "United States", flag: "🇺🇸" },
    { name: "Craig Stephens", country: "United States", flag: "🇺🇸" },
    { name: "Jacqueline Butler", country: "United States", flag: "🇺🇸" },
    { name: "Dale Saunders", country: "United States", flag: "🇺🇸" },
    { name: "Erica Webb", country: "United States", flag: "🇺🇸" },
    { name: "Travis Freeman", country: "United States", flag: "🇺🇸" },
    { name: "Sabrina Perkins", country: "United States", flag: "🇺🇸" },

    // ── UNITED KINGDOM (35 names) ──────────────────────────────────────────
    { name: "Emma Sutton", country: "United Kingdom", flag: "🇬🇧" },
    { name: "Oliver James", country: "United Kingdom", flag: "🇬🇧" },
    { name: "Charlotte Walsh", country: "United Kingdom", flag: "🇬🇧" },
    { name: "Harry Bennett", country: "United Kingdom", flag: "🇬🇧" },
    { name: "Sophie Turner", country: "United Kingdom", flag: "🇬🇧" },
    { name: "George Mason", country: "United Kingdom", flag: "🇬🇧" },
    { name: "Amelia Rose", country: "United Kingdom", flag: "🇬🇧" },
    { name: "Jack Davies", country: "United Kingdom", flag: "🇬🇧" },
    { name: "Isla Kirk", country: "United Kingdom", flag: "🇬🇧" },
    { name: "Noah Lambert", country: "United Kingdom", flag: "🇬🇧" },
    { name: "Poppy Hughes", country: "United Kingdom", flag: "🇬🇧" },
    { name: "Thomas Clarke", country: "United Kingdom", flag: "🇬🇧" },
    { name: "Lily Ford", country: "United Kingdom", flag: "🇬🇧" },
    { name: "Oscar Price", country: "United Kingdom", flag: "🇬🇧" },
    { name: "Freya Norris", country: "United Kingdom", flag: "🇬🇧" },
    { name: "William Grant", country: "United Kingdom", flag: "🇬🇧" },
    { name: "Grace Vickers", country: "United Kingdom", flag: "🇬🇧" },
    { name: "James Rowe", country: "United Kingdom", flag: "🇬🇧" },
    { name: "Ava Morton", country: "United Kingdom", flag: "🇬🇧" },
    { name: "Charlie Barker", country: "United Kingdom", flag: "🇬🇧" },
    { name: "Evie Nash", country: "United Kingdom", flag: "🇬🇧" },
    { name: "Freddie Cross", country: "United Kingdom", flag: "🇬🇧" },
    { name: "Millie Cooper", country: "United Kingdom", flag: "🇬🇧" },
    { name: "Alfie Fletcher", country: "United Kingdom", flag: "🇬🇧" },
    { name: "Rosie Chambers", country: "United Kingdom", flag: "🇬🇧" },
    { name: "Archie Holt", country: "United Kingdom", flag: "🇬🇧" },
    { name: "Daisy Newton", country: "United Kingdom", flag: "🇬🇧" },
    { name: "Leo Pearce", country: "United Kingdom", flag: "🇬🇧" },
    { name: "Ruby Watkins", country: "United Kingdom", flag: "🇬🇧" },
    { name: "Theo Holland", country: "United Kingdom", flag: "🇬🇧" },
    { name: "Phoebe Sinclair", country: "United Kingdom", flag: "🇬🇧" },
    { name: "Max Burton", country: "United Kingdom", flag: "🇬🇧" },
    { name: "Harriet Page", country: "United Kingdom", flag: "🇬🇧" },
    { name: "Finn Morgan", country: "United Kingdom", flag: "🇬🇧" },
    { name: "Imogen Bell", country: "United Kingdom", flag: "🇬🇧" },

    // ── GERMANY (25 names) ─────────────────────────────────────────────────
    { name: "Anna Mueller", country: "Germany", flag: "🇩🇪" },
    { name: "Hans Klein", country: "Germany", flag: "🇩🇪" },
    { name: "Klaus Werner", country: "Germany", flag: "🇩🇪" },
    { name: "Greta Schmidt", country: "Germany", flag: "🇩🇪" },
    { name: "Stefan Bauer", country: "Germany", flag: "🇩🇪" },
    { name: "Petra Lang", country: "Germany", flag: "🇩🇪" },
    { name: "Markus Hoffmann", country: "Germany", flag: "🇩🇪" },
    { name: "Sabine Richter", country: "Germany", flag: "🇩🇪" },
    { name: "Lukas Fischer", country: "Germany", flag: "🇩🇪" },
    { name: "Julia Neumann", country: "Germany", flag: "🇩🇪" },
    { name: "Thomas Drescher", country: "Germany", flag: "🇩🇪" },
    { name: "Kathrin Gruber", country: "Germany", flag: "🇩🇪" },
    { name: "Michael Pfeiffer", country: "Germany", flag: "🇩🇪" },
    { name: "Monika Vogt", country: "Germany", flag: "🇩🇪" },
    { name: "Felix Conrad", country: "Germany", flag: "🇩🇪" },
    { name: "Nina Schreiber", country: "Germany", flag: "🇩🇪" },
    { name: "Jonas Braun", country: "Germany", flag: "🇩🇪" },
    { name: "Laura Weber", country: "Germany", flag: "🇩🇪" },
    { name: "Tobias Lehmann", country: "Germany", flag: "🇩🇪" },
    { name: "Eva Zimmermann", country: "Germany", flag: "🇩🇪" },
    { name: "Simon Kruse", country: "Germany", flag: "🇩🇪" },
    { name: "Hannah Mayer", country: "Germany", flag: "🇩🇪" },
    { name: "Patrick Hartmann", country: "Germany", flag: "🇩🇪" },
    { name: "Lena Schwarz", country: "Germany", flag: "🇩🇪" },
    { name: "Florian Koenig", country: "Germany", flag: "🇩🇪" },

    // ── FRANCE (20 names) ──────────────────────────────────────────────────
    { name: "Sophie Leclerc", country: "France", flag: "🇫🇷" },
    { name: "Pierre Dupont", country: "France", flag: "🇫🇷" },
    { name: "Marie Curie", country: "France", flag: "🇫🇷" },
    { name: "Jean-Luc Roche", country: "France", flag: "🇫🇷" },
    { name: "Camille Bernard", country: "France", flag: "🇫🇷" },
    { name: "Antoine Moreau", country: "France", flag: "🇫🇷" },
    { name: "Isabelle Hernandez", country: "France", flag: "🇫🇷" },
    { name: "Louis Faure", country: "France", flag: "🇫🇷" },
    { name: "Chloé Noel", country: "France", flag: "🇫🇷" },
    { name: "Nicolas Perrin", country: "France", flag: "🇫🇷" },
    { name: "Emilie Guerin", country: "France", flag: "🇫🇷" },
    { name: "Julien Vidal", country: "France", flag: "🇫🇷" },
    { name: "Manon Clement", country: "France", flag: "🇫🇷" },
    { name: "Baptiste Renard", country: "France", flag: "🇫🇷" },
    { name: "Lea Gaudin", country: "France", flag: "🇫🇷" },
    { name: "Quentin Dumas", country: "France", flag: "🇫🇷" },
    { name: "Pauline Mercier", country: "France", flag: "🇫🇷" },
    { name: "Clement Fontaine", country: "France", flag: "🇫🇷" },
    { name: "Alice Lefebvre", country: "France", flag: "🇫🇷" },
    { name: "Hugo Chevalier", country: "France", flag: "🇫🇷" },

    // ── BRAZIL (20 names) ──────────────────────────────────────────────────
    { name: "Carlos Goncalves", country: "Brazil", flag: "🇧🇷" },
    { name: "Gabriela Santos", country: "Brazil", flag: "🇧🇷" },
    { name: "Lucas Machado", country: "Brazil", flag: "🇧🇷" },
    { name: "Juliana Pereira", country: "Brazil", flag: "🇧🇷" },
    { name: "Rafael Oliveira", country: "Brazil", flag: "🇧🇷" },
    { name: "Fernanda Teixeira", country: "Brazil", flag: "🇧🇷" },
    { name: "Bruno Lima", country: "Brazil", flag: "🇧🇷" },
    { name: "Amanda Rocha", country: "Brazil", flag: "🇧🇷" },
    { name: "Pedro Kowalski", country: "Brazil", flag: "🇧🇷" },
    { name: "Beatriz Dias", country: "Brazil", flag: "🇧🇷" },
    { name: "Thiago Vieira", country: "Brazil", flag: "🇧🇷" },
    { name: "Larissa Nunes", country: "Brazil", flag: "🇧🇷" },
    { name: "Matheus Barbosa", country: "Brazil", flag: "🇧🇷" },
    { name: "Camila Ribeiro", country: "Brazil", flag: "🇧🇷" },
    { name: "Felipe Carvalho", country: "Brazil", flag: "🇧🇷" },
    { name: "Leticia Araujo", country: "Brazil", flag: "🇧🇷" },
    { name: "Diego Ferreira", country: "Brazil", flag: "🇧🇷" },
    { name: "Vanessa Alves", country: "Brazil", flag: "🇧🇷" },
    { name: "Rodrigo Costa", country: "Brazil", flag: "🇧🇷" },
    { name: "Patricia Nascimento", country: "Brazil", flag: "🇧🇷" },

    // ── JAPAN (20 names) ───────────────────────────────────────────────────
    { name: "Yuki Tanaka", country: "Japan", flag: "🇯🇵" },
    { name: "Hiroshi Nakamura", country: "Japan", flag: "🇯🇵" },
    { name: "Sakura Kimura", country: "Japan", flag: "🇯🇵" },
    { name: "Takeshi Matsumoto", country: "Japan", flag: "🇯🇵" },
    { name: "Yumi Suzuki", country: "Japan", flag: "🇯🇵" },
    { name: "Kenji Yamamoto", country: "Japan", flag: "🇯🇵" },
    { name: "Akiko Kobayashi", country: "Japan", flag: "🇯🇵" },
    { name: "Daichi Ito", country: "Japan", flag: "🇯🇵" },
    { name: "Haruka Watanabe", country: "Japan", flag: "🇯🇵" },
    { name: "Ryo Sato", country: "Japan", flag: "🇯🇵" },
    { name: "Nana Yamada", country: "Japan", flag: "🇯🇵" },
    { name: "Sota Hayashi", country: "Japan", flag: "🇯🇵" },
    { name: "Aoi Inoue", country: "Japan", flag: "🇯🇵" },
    { name: "Kaito Kato", country: "Japan", flag: "🇯🇵" },
    { name: "Hana Yoshida", country: "Japan", flag: "🇯🇵" },
    { name: "Ryota Yamashita", country: "Japan", flag: "🇯🇵" },
    { name: "Misaki Nakagawa", country: "Japan", flag: "🇯🇵" },
    { name: "Yuta Fujita", country: "Japan", flag: "🇯🇵" },
    { name: "Rin Okaomoto", country: "Japan", flag: "🇯🇵" },
    { name: "Shun Ikeda", country: "Japan", flag: "🇯🇵" },

    // ── CHINA (20 names) ───────────────────────────────────────────────────
    { name: "Li Wei", country: "China", flag: "🇨🇳" },
    { name: "Wang Fang", country: "China", flag: "🇨🇳" },
    { name: "Zhang Min", country: "China", flag: "🇨🇳" },
    { name: "Liu Yang", country: "China", flag: "🇨🇳" },
    { name: "Chen Xiao", country: "China", flag: "🇨🇳" },
    { name: "Wu Jing", country: "China", flag: "🇨🇳" },
    { name: "Huang Lei", country: "China", flag: "🇨🇳" },
    { name: "Zhao Ying", country: "China", flag: "🇨🇳" },
    { name: "Zhou Na", country: "China", flag: "🇨🇳" },
    { name: "Xu Long", country: "China", flag: "🇨🇳" },
    { name: "Sun Mei", country: "China", flag: "🇨🇳" },
    { name: "Ma Qiang", country: "China", flag: "🇨🇳" },
    { name: "He Yun", country: "China", flag: "🇨🇳" },
    { name: "Gao Peng", country: "China", flag: "🇨🇳" },
    { name: "Lin Xia", country: "China", flag: "🇨🇳" },
    { name: "Deng Rui", country: "China", flag: "🇨🇳" },
    { name: "Zeng Hui", country: "China", flag: "🇨🇳" },
    { name: "Cao Kun", country: "China", flag: "🇨🇳" },
    { name: "Pan Shan", country: "China", flag: "🇨🇳" },
    { name: "Tang Bo", country: "China", flag: "🇨🇳" },

    // ── UAE (15 names) ─────────────────────────────────────────────────────
    { name: "Mohammed Al Rashid", country: "UAE", flag: "🇦🇪" },
    { name: "Fatima Al Hamdan", country: "UAE", flag: "🇦🇪" },
    { name: "Ahmed Khalil", country: "UAE", flag: "🇦🇪" },
    { name: "Layla Mansoor", country: "UAE", flag: "🇦🇪" },
    { name: "Omar Saeed", country: "UAE", flag: "🇦🇪" },
    { name: "Aisha Darwish", country: "UAE", flag: "🇦🇪" },
    { name: "Ali Nasser", country: "UAE", flag: "🇦🇪" },
    { name: "Mariam Farooq", country: "UAE", flag: "🇦🇪" },
    { name: "Khalid Butti", country: "UAE", flag: "🇦🇪" },
    { name: "Noura Al Mazrouei", country: "UAE", flag: "🇦🇪" },
    { name: "Hamad Al Suwaidi", country: "UAE", flag: "🇦🇪" },
    { name: "Sara Al Falasi", country: "UAE", flag: "🇦🇪" },
    { name: "Rashed Al Ketbi", country: "UAE", flag: "🇦🇪" },
    { name: "Hessa Al Shamsi", country: "UAE", flag: "🇦🇪" },
    { name: "Saeed Al Kaabi", country: "UAE", flag: "🇦🇪" },

    // ── AUSTRALIA (20 names) ───────────────────────────────────────────────
    { name: "Olivia Watson", country: "Australia", flag: "🇦🇺" },
    { name: "Liam Johnson", country: "Australia", flag: "🇦🇺" },
    { name: "Emma Kelly", country: "Australia", flag: "🇦🇺" },
    { name: "Noah Burns", country: "Australia", flag: "🇦🇺" },
    { name: "Mia Ross", country: "Australia", flag: "🇦🇺" },
    { name: "Lucas Hart", country: "Australia", flag: "🇦🇺" },
    { name: "Chloe Murphy", country: "Australia", flag: "🇦🇺" },
    { name: "Ethan Dixon", country: "Australia", flag: "🇦🇺" },
    { name: "Charlotte Ford", country: "Australia", flag: "🇦🇺" },
    { name: "Jack Newman", country: "Australia", flag: "🇦🇺" },
    { name: "Amelia Cooper", country: "Australia", flag: "🇦🇺" },
    { name: "Henry Powell", country: "Australia", flag: "🇦🇺" },
    { name: "Sophie Lane", country: "Australia", flag: "🇦🇺" },
    { name: "Mason Riley", country: "Australia", flag: "🇦🇺" },
    { name: "Grace Spencer", country: "Australia", flag: "🇦🇺" },
    { name: "Ava Tucker", country: "Australia", flag: "🇦🇺" },
    { name: "James Hughes", country: "Australia", flag: "🇦🇺" },
    { name: "Isla Bryant", country: "Australia", flag: "🇦🇺" },
    { name: "William Crawford", country: "Australia", flag: "🇦🇺" },
    { name: "Ruby Miles", country: "Australia", flag: "🇦🇺" },

    // ── CANADA (18 names) ──────────────────────────────────────────────────
    { name: "Ryan McDonald", country: "Canada", flag: "🇨🇦" },
    { name: "Emily Torres", country: "Canada", flag: "🇨🇦" },
    { name: "Jacob Wright", country: "Canada", flag: "🇨🇦" },
    { name: "Hannah Lee", country: "Canada", flag: "🇨🇦" },
    { name: "Liam King", country: "Canada", flag: "🇨🇦" },
    { name: "Sophia Moore", country: "Canada", flag: "🇨🇦" },
    { name: "Ethan Clark", country: "Canada", flag: "🇨🇦" },
    { name: "Olivia Brown", country: "Canada", flag: "🇨🇦" },
    { name: "Daniel Martin", country: "Canada", flag: "🇨🇦" },
    { name: "Emma Wilson", country: "Canada", flag: "🇨🇦" },
    { name: "Noah Davis", country: "Canada", flag: "🇨🇦" },
    { name: "Ava Taylor", country: "Canada", flag: "🇨🇦" },
    { name: "Lucas Anderson", country: "Canada", flag: "🇨🇦" },
    { name: "Mia Thomas", country: "Canada", flag: "🇨🇦" },
    { name: "James Jackson", country: "Canada", flag: "🇨🇦" },
    { name: "Isabella White", country: "Canada", flag: "🇨🇦" },
    { name: "Alexander Harris", country: "Canada", flag: "🇨🇦" },
    { name: "Charlotte Thompson", country: "Canada", flag: "🇨🇦" },

    // ── MEXICO (15 names) ──────────────────────────────────────────────────
    { name: "Diego Martinez", country: "Mexico", flag: "🇲🇽" },
    { name: "Sofia Rodriguez", country: "Mexico", flag: "🇲🇽" },
    { name: "Miguel Hernandez", country: "Mexico", flag: "🇲🇽" },
    { name: "Valentina Garcia", country: "Mexico", flag: "🇲🇽" },
    { name: "Alejandro Lopez", country: "Mexico", flag: "🇲🇽" },
    { name: "Camila Gonzalez", country: "Mexico", flag: "🇲🇽" },
    { name: "Luis Ramirez", country: "Mexico", flag: "🇲🇽" },
    { name: "Isabella Torres", country: "Mexico", flag: "🇲🇽" },
    { name: "Jose Vazquez", country: "Mexico", flag: "🇲🇽" },
    { name: "Fernanda Diaz", country: "Mexico", flag: "🇲🇽" },
    { name: "Carlos Morales", country: "Mexico", flag: "🇲🇽" },
    { name: "Ana Reyes", country: "Mexico", flag: "🇲🇽" },
    { name: "Francisco Cruz", country: "Mexico", flag: "🇲🇽" },
    { name: "Mariana Flores", country: "Mexico", flag: "🇲🇽" },
    { name: "Jorge Rivera", country: "Mexico", flag: "🇲🇽" },

    // ── ITALY (15 names) ───────────────────────────────────────────────────
    { name: "Isabella Russo", country: "Italy", flag: "🇮🇹" },
    { name: "Marco Vitali", country: "Italy", flag: "🇮🇹" },
    { name: "Giulia Bianchi", country: "Italy", flag: "🇮🇹" },
    { name: "Alessandro Ferrari", country: "Italy", flag: "🇮🇹" },
    { name: "Sofia Marino", country: "Italy", flag: "🇮🇹" },
    { name: "Lorenzo De Rosa", country: "Italy", flag: "🇮🇹" },
    { name: "Francesca Greco", country: "Italy", flag: "🇮🇹" },
    { name: "Matteo Lombardi", country: "Italy", flag: "🇮🇹" },
    { name: "Chiara Leone", country: "Italy", flag: "🇮🇹" },
    { name: "Andrea Pellegrini", country: "Italy", flag: "🇮🇹" },
    { name: "Valentina Ricci", country: "Italy", flag: "🇮🇹" },
    { name: "Luca Conti", country: "Italy", flag: "🇮🇹" },
    { name: "Sara Esposito", country: "Italy", flag: "🇮🇹" },
    { name: "Davide Costa", country: "Italy", flag: "🇮🇹" },
    { name: "Elena Mancini", country: "Italy", flag: "🇮🇹" },

    // ── SPAIN (12 names) ───────────────────────────────────────────────────
    { name: "Maria Castillo", country: "Spain", flag: "🇪🇸" },
    { name: "Carlos Lopez", country: "Spain", flag: "🇪🇸" },
    { name: "Elena Martinez", country: "Spain", flag: "🇪🇸" },
    { name: "Javier Romero", country: "Spain", flag: "🇪🇸" },
    { name: "Laura Fernandez", country: "Spain", flag: "🇪🇸" },
    { name: "David Navarro", country: "Spain", flag: "🇪🇸" },
    { name: "Ana Jimenez", country: "Spain", flag: "🇪🇸" },
    { name: "Pablo Vargas", country: "Spain", flag: "🇪🇸" },
    { name: "Isabel Campos", country: "Spain", flag: "🇪🇸" },
    { name: "Sergio Gil", country: "Spain", flag: "🇪🇸" },
    { name: "Carmen Ortega", country: "Spain", flag: "🇪🇸" },
    { name: "Antonio Molina", country: "Spain", flag: "🇪🇸" },

    // ── SOUTH KOREA (12 names) ─────────────────────────────────────────────
    { name: "Min-Jun Kim", country: "South Korea", flag: "🇰🇷" },
    { name: "Seo-Yun Lee", country: "South Korea", flag: "🇰🇷" },
    { name: "Ji-Hoon Park", country: "South Korea", flag: "🇰🇷" },
    { name: "Hye-Jin Choi", country: "South Korea", flag: "🇰🇷" },
    { name: "Tae-Yang Moon", country: "South Korea", flag: "🇰🇷" },
    { name: "Eun-Ji Woo", country: "South Korea", flag: "🇰🇷" },
    { name: "Jae-Won Shin", country: "South Korea", flag: "🇰🇷" },
    { name: "Soo-Ah Jung", country: "South Korea", flag: "🇰🇷" },
    { name: "Dong-Hyun Oh", country: "South Korea", flag: "🇰🇷" },
    { name: "Yu-Ri Han", country: "South Korea", flag: "🇰🇷" },
    { name: "Seung-Hyun Kang", country: "South Korea", flag: "🇰🇷" },
    { name: "Ji-Young Yoon", country: "South Korea", flag: "🇰🇷" },

    // ── NETHERLANDS (10 names) ─────────────────────────────────────────────
    { name: "Lars Kuipers", country: "Netherlands", flag: "🇳🇱" },
    { name: "Emma Visser", country: "Netherlands", flag: "🇳🇱" },
    { name: "Daan Bakker", country: "Netherlands", flag: "🇳🇱" },
    { name: "Sophie de Vries", country: "Netherlands", flag: "🇳🇱" },
    { name: "Thijs Meijer", country: "Netherlands", flag: "🇳🇱" },
    { name: "Lisa den Berg", country: "Netherlands", flag: "🇳🇱" },
    { name: "Sander Smit", country: "Netherlands", flag: "🇳🇱" },
    { name: "Anna van Dijk", country: "Netherlands", flag: "🇳🇱" },
    { name: "Nick Bos", country: "Netherlands", flag: "🇳🇱" },
    { name: "Iris Mulder", country: "Netherlands", flag: "🇳🇱" },

    // ── SINGAPORE (10 names) ───────────────────────────────────────────────
    { name: "Wei Ting Lim", country: "Singapore", flag: "🇸🇬" },
    { name: "Kai En Tan", country: "Singapore", flag: "🇸🇬" },
    { name: "Li Hua Chen", country: "Singapore", flag: "🇸🇬" },
    { name: "Siti Aminah", country: "Singapore", flag: "🇸🇬" },
    { name: "Arjun Tiwari", country: "Singapore", flag: "🇸🇬" },
    { name: "Priya Menon", country: "Singapore", flag: "🇸🇬" },
    { name: "Jun Hao Wong", country: "Singapore", flag: "🇸🇬" },
    { name: "Xiu Ying Ng", country: "Singapore", flag: "🇸🇬" },
    { name: "Rahul Pillai", country: "Singapore", flag: "🇸🇬" },
    { name: "Mei Xuan Ong", country: "Singapore", flag: "🇸🇬" },

    // ── TURKEY (10 names) ──────────────────────────────────────────────────
    { name: "Ahmet Yilmaz", country: "Turkey", flag: "🇹🇷" },
    { name: "Zeynep Kaya", country: "Turkey", flag: "🇹🇷" },
    { name: "Mehmet Demir", country: "Turkey", flag: "🇹🇷" },
    { name: "Ayse Celik", country: "Turkey", flag: "🇹🇷" },
    { name: "Mustafa Sahin", country: "Turkey", flag: "🇹🇷" },
    { name: "Elif Arslan", country: "Turkey", flag: "🇹🇷" },
    { name: "Ibrahim Koc", country: "Turkey", flag: "🇹🇷" },
    { name: "Fatma Ozturk", country: "Turkey", flag: "🇹🇷" },
    { name: "Ali Erdogan", country: "Turkey", flag: "🇹🇷" },
    { name: "Merve Aydın", country: "Turkey", flag: "🇹🇷" },

    // ── RUSSIA (10 names) ──────────────────────────────────────────────────
    { name: "Ivan Petrov", country: "Russia", flag: "🇷🇺" },
    { name: "Natasha Sokolova", country: "Russia", flag: "🇷🇺" },
    { name: "Dmitry Volkov", country: "Russia", flag: "🇷🇺" },
    { name: "Olga Novikova", country: "Russia", flag: "🇷🇺" },
    { name: "Alexei Morozov", country: "Russia", flag: "🇷🇺" },
    { name: "Elena Kozlova", country: "Russia", flag: "🇷🇺" },
    { name: "Sergei Popov", country: "Russia", flag: "🇷🇺" },
    { name: "Mikhail Lebedev", country: "Russia", flag: "🇷🇺" },
    { name: "Anna Semenova", country: "Russia", flag: "🇷🇺" },
    { name: "Pavel Fedorov", country: "Russia", flag: "🇷🇺" },

    // ── EGYPT (8 names) ────────────────────────────────────────────────────
    { name: "Ahmed Hassan", country: "Egypt", flag: "🇪🇬" },
    { name: "Nour Mohamed", country: "Egypt", flag: "🇪🇬" },
    { name: "Kareem Ibrahim", country: "Egypt", flag: "🇪🇬" },
    { name: "Mariam Khalil", country: "Egypt", flag: "🇪🇬" },
    { name: "Omar Samir", country: "Egypt", flag: "🇪🇬" },
    { name: "Sara Mahmoud", country: "Egypt", flag: "🇪🇬" },
    { name: "Youssef Ali", country: "Egypt", flag: "🇪🇬" },
    { name: "Rania Farouk", country: "Egypt", flag: "🇪🇬" },

    // ── NIGERIA (8 names) ──────────────────────────────────────────────────
    { name: "Emeka Okafor", country: "Nigeria", flag: "🇳🇬" },
    { name: "Amara Adeyemi", country: "Nigeria", flag: "🇳🇬" },
    { name: "Chidi Obi", country: "Nigeria", flag: "🇳🇬" },
    { name: "Ngozi Eze", country: "Nigeria", flag: "🇳🇬" },
    { name: "Tunde Bakare", country: "Nigeria", flag: "🇳🇬" },
    { name: "Funmi Adeleke", country: "Nigeria", flag: "🇳🇬" },
    { name: "Rotimi Lawal", country: "Nigeria", flag: "🇳🇬" },
    { name: "Chisom Nwosu", country: "Nigeria", flag: "🇳🇬" },

    // ── SOUTH AFRICA (8 names) ─────────────────────────────────────────────
    { name: "Lethabo Dlamini", country: "South Africa", flag: "🇿🇦" },
    { name: "Naledi Sithole", country: "South Africa", flag: "🇿🇦" },
    { name: "Sipho Nkosi", country: "South Africa", flag: "🇿🇦" },
    { name: "Thandi Mahlangu", country: "South Africa", flag: "🇿🇦" },
    { name: "Andile Zulu", country: "South Africa", flag: "🇿🇦" },
    { name: "Ayanda Khumalo", country: "South Africa", flag: "🇿🇦" },
    { name: "Bongani Ntuli", country: "South Africa", flag: "🇿🇦" },
    { name: "Zanele Mokoena", country: "South Africa", flag: "🇿🇦" },

    // ── SWEDEN (8 names) ───────────────────────────────────────────────────
    { name: "Erik Johansson", country: "Sweden", flag: "🇸🇪" },
    { name: "Anna Lindstrom", country: "Sweden", flag: "🇸🇪" },
    { name: "Lars Eriksson", country: "Sweden", flag: "🇸🇪" },
    { name: "Maja Karlsson", country: "Sweden", flag: "🇸🇪" },
    { name: "Oscar Nilsson", country: "Sweden", flag: "🇸🇪" },
    { name: "Elsa Magnusson", country: "Sweden", flag: "🇸🇪" },
    { name: "Gustav Holm", country: "Sweden", flag: "🇸🇪" },
    { name: "Frida Persson", country: "Sweden", flag: "🇸🇪" },

    // ── MALAYSIA (8 names) ─────────────────────────────────────────────────
    { name: "Ahmad Razif", country: "Malaysia", flag: "🇲🇾" },
    { name: "Nurul Aina", country: "Malaysia", flag: "🇲🇾" },
    { name: "Haziq Zain", country: "Malaysia", flag: "🇲🇾" },
    { name: "Syafiqa Roslan", country: "Malaysia", flag: "🇲🇾" },
    { name: "Darwisyah Lim", country: "Malaysia", flag: "🇲🇾" },
    { name: "Suhana Tan", country: "Malaysia", flag: "🇲🇾" },
    { name: "Imran Hakim", country: "Malaysia", flag: "🇲🇾" },
    { name: "Fatihah Yusof", country: "Malaysia", flag: "🇲🇾" },

    // ── PHILIPPINES (8 names) ──────────────────────────────────────────────
    { name: "Juan Santos", country: "Philippines", flag: "🇵🇭" },
    { name: "Maria Reyes", country: "Philippines", flag: "🇵🇭" },
    { name: "Jose Cruz", country: "Philippines", flag: "🇵🇭" },
    { name: "Ana Bautista", country: "Philippines", flag: "🇵🇭" },
    { name: "Marco Villanueva", country: "Philippines", flag: "🇵🇭" },
    { name: "Celine Aguilar", country: "Philippines", flag: "🇵🇭" },
    { name: "Andres Dela Cruz", country: "Philippines", flag: "🇵🇭" },
    { name: "Jasmine Pascual", country: "Philippines", flag: "🇵🇭" },

    // ── ARGENTINA (8 names) ────────────────────────────────────────────────
    { name: "Matias Gonzalez", country: "Argentina", flag: "🇦🇷" },
    { name: "Lucia Fernandez", country: "Argentina", flag: "🇦🇷" },
    { name: "Santiago Lopez", country: "Argentina", flag: "🇦🇷" },
    { name: "Valentina Perez", country: "Argentina", flag: "🇦🇷" },
    { name: "Facundo Martinez", country: "Argentina", flag: "🇦🇷" },
    { name: "Camila Romero", country: "Argentina", flag: "🇦🇷" },
    { name: "Agustin Torres", country: "Argentina", flag: "🇦🇷" },
    { name: "Florencia Diaz", country: "Argentina", flag: "🇦🇷" },
];
